default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  password: 1234
  username: postgres
  pool: 5

development:
  <<: *default
  database: escamboapp_development

test:
  <<: *default
  database: escamboapp_test

production:
  <<: *default
  database: escamboapp_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 15
